on:
  push:
    branches:
      - main

name: Percy Visual Testing
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run "start:server"
      - run: npm run "percy:cypress"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
